@startuml
actor "Пользователь" as user
participant "API биллинга" as billing
participant "Платежная система" as bank
participant "Callback API" as api
database "База данных" as db
queue "Очередь на печать чеков" as receipts
participant "Worker печати чеков" as rWorker


user -> billing: Запросить платежное окно
billing -> db: Сохранить идентификатор платежа
billing -> user: URL
user -> bank: GET https://url
bank -> user: HTML + JS
user -> bank: payment data
bank -> bank: Платежная магия

bank -> api: Уведомление о статусе операции
    api -> db: Найти идентификатор платежа
alt "Оплата успешна"
    api -> db: Сохранить информацию о платеже
    api -> db: Поставить задачу на пересчет задолженности
    api -> receipts: Положить чек в очередь

else "Оплата не удалась"
    api -> db: Пометить платеж неудачным
end

api -> bank: 200 OK

receipts -> rWorker: Взять чек
rWorker -> bank: Напечатать чек
bank -> rWorker: 200 OK

@enduml